#! /bin/bash

sudo chown root:root /home/sovol/ota_service.sh
sudo mv /home/sovol/ota_service.sh /boot/scripts/

target_dir="/home/sovol"
sudo chown -R sovol:sovol $target_dir

#usb
cd /home/sovol/usbmount
sudo make install

#patch
cd /home/sovol/patch
sudo chmod +x ./patch.sh
sudo ./patch.sh

cd ~

sync
echo "File permissions changed successfully."
