#!/bin/sh

log_path="/home/sovol/printer_data/logs/usbmount.log"

install_deb_package() {
    local deb_file=$(find /tmp -type f -name "SV08mini_Update_Package*.deb")
    echo "Installing $deb_file" >> "$log_path"
    sudo dpkg -i "$deb_file" >> "$log_path" 2>&1
    if [ $? -eq 0 ]; then
        echo "deb package install success!" >> "$log_path"
        sudo rm -rf "$deb_file"
        (sleep 2 && reboot) &
    else
        echo "deb package install fail!" >> "$log_path"
    fi
}

mediadir="/home/sovol/printer_data/gcodes/USB"
source_dir="$mediadir"
target_dir="/home/sovol/printer_data/gcodes"
dev=/dev/${1##*/}

if ! [ -b "$dev" ]; then
    if grep /etc/mtab -qe "^$dev"; then
        rm -f /home/sovol/printer_data/gcodes/USB-*.gcode
        umount "$dev"
        echo "umount $dev success" >> "$log_path"
        rmdir "$mediadir"
    fi
    exit 0
fi

echo "exec mount $1" >> "$log_path"
mkdir -p "$mediadir"
if ! sudo mount -t auto -o uid=sovol -o gid=sovol "$dev" "$mediadir" >> "$log_path" 2>&1; then
    echo "Mount $dev failed" >> "$log_path"
    exit 1
fi

prefix="USB-"

for file in "$source_dir"/*.gcode; do
    filename=$(basename "$file")
    target_file="$target_dir/$prefix$filename"
    cp "$file" "$target_file"
done

CONFIG_FILE="$source_dir/wifi.cfg"

if [ -f "$CONFIG_FILE" ]; then
    SSID=$(sed -n -E 's/^ssid[[:space:]]*=[[:space:]]*//p' "$CONFIG_FILE" | tr -d '\r' | head -n 1)
    PASSWORD=$(sed -n -E 's/^password[[:space:]]*=[[:space:]]*//p' "$CONFIG_FILE" | tr -d '\r' | head -n 1)

    CURRENT_SSID=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d':' -f2)

    if [ "$CURRENT_SSID" = "$SSID" ]; then
        echo "Already connected to $SSID." >> "$log_path"
    else
        echo "Connecting to SSID: $SSID" >> "$log_path"
        nmcli dev wifi connect "$SSID" password "$PASSWORD" >> "$log_path" 2>&1
        [ $? -eq 0 ] && echo "Connected to $SSID successfully." >> "$log_path" || echo "Failed to connect to $SSID." >> "$log_path"
    fi
else
    echo "WiFi config file not found at $CONFIG_FILE" >> "$log_path"
fi

[ -f "$mediadir/test.sh" ] && bash "$mediadir/test.sh" >> "$log_path" 2>&1

production_mode_dir="$source_dir/Sovol_Production_Mode"

if [ -d "$production_mode_dir" ]; then
    deb_file=$(find "$production_mode_dir" -type f -name "SV08mini_Update_Package*.deb" | tr -d '\n\r')
    if [ -n "$deb_file" ]; then
        if grep -q "$deb_file" "$log_path"; then
            echo "$deb_file has been installed" >> "$log_path"
        else
            echo "Installing new package: $deb_file" >> "$log_path"
            echo "Timestamp: $(date)" >> "$log_path"
            sudo cp "$deb_file" /tmp
            install_deb_package
        fi
    fi
else
    deb_file=$(find "$target_dir" -type f -name "SV08mini_Update_Package*.deb")
    if [ -n "$deb_file" ]; then
        echo "Timestamp: $(date)" >> "$log_path"
        sudo mv "$deb_file" /tmp
        install_deb_package
    fi
fi
